# -*- coding: utf-8 -*-
"""Test_PointNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ma54XFSNeoNqgjZZufkAzJT9mUlMQMn0
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/WORK/03-PointNet"

"""---
## Test PointNet Mode
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd "./pointnet/"
!python3 model.py

"""---
## Test Utils
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd "./utils/"
!python3 ./show3d_balls.py

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/WORK/03-PointNet/Show_PointCloud"

import numpy as np
import ctypes as ct
import os

# =========================
# Load shared library safely
# =========================
lib_path = os.path.abspath("./render_balls_so.so")
dll = ct.CDLL(lib_path)

# =========================
# Define C function prototype
# void render_ball(
#   int H, int W,
#   uint8_t* image,
#   int N,
#   int32_t* xyz,
#   float* c0, float* c1, float* c2,
#   int radius
# )
# =========================
dll.render_ball.argtypes = [
    ct.c_int,                      # H
    ct.c_int,                      # W
    ct.c_void_p,                   # image buffer
    ct.c_int,                      # number of points
    ct.c_void_p,                   # xyz (int32)
    ct.c_void_p,                   # c0
    ct.c_void_p,                   # c1
    ct.c_void_p,                   # c2
    ct.c_int                       # radius
]
dll.render_ball.restype = None


# =========================
# Safe render function
# =========================
def render_points_safe(
    xyz,
    colors=None,
    image_size=800,
    ball_radius=5,
    background=(0, 0, 0)
):
    assert xyz.ndim == 2 and xyz.shape[1] == 3, "xyz must be Nx3"

    # ---------- Normalize & center ----------
    xyz = xyz.astype(np.float32)
    xyz = xyz - xyz.mean(axis=0)
    r = np.linalg.norm(xyz, axis=1).max()
    xyz = xyz / (r * 2.2)
    xyz = xyz * image_size + image_size / 2

    xyz_i = np.require(xyz.astype(np.int32), requirements=["C"])

    n_points = xyz_i.shape[0]

    # ---------- Colors ----------
    if colors is None:
        c0 = np.full(n_points, 255, dtype=np.float32)
        c1 = np.full(n_points, 255, dtype=np.float32)
        c2 = np.full(n_points, 255, dtype=np.float32)
    else:
        assert colors.shape == (n_points, 3)
        c0 = colors[:, 0].astype(np.float32)
        c1 = colors[:, 1].astype(np.float32)
        c2 = colors[:, 2].astype(np.float32)

    c0 = np.require(c0, requirements=["C"])
    c1 = np.require(c1, requirements=["C"])
    c2 = np.require(c2, requirements=["C"])

    # ---------- Output image ----------
    image = np.zeros((image_size, image_size, 3), dtype=np.uint8)
    image[:] = background

    # ---------- Call C safely ----------
    dll.render_ball(
        ct.c_int(image_size),
        ct.c_int(image_size),
        image.ctypes.data_as(ct.c_void_p),
        ct.c_int(n_points),
        xyz_i.ctypes.data_as(ct.c_void_p),
        c0.ctypes.data_as(ct.c_void_p),
        c1.ctypes.data_as(ct.c_void_p),
        c2.ctypes.data_as(ct.c_void_p),
        ct.c_int(ball_radius)
    )

    return image


# =========================
# Test
# =========================
if __name__ == "__main__":
    #np.random.seed(0)
    #points = np.random.randn(1024, 3) #(2000, 3)
    # Load the .npy file
    num_selected_sample = 450
    data = np.load('radar_data_test.npy')
    data = np.load('radar_data_test.npy')
    labels = np.load('radar_labels_test.npy')
    point_test = data[num_selected_sample]
    label_test = labels[num_selected_sample]
    point3D = point_test[:, :3]
    img = render_points_safe(point3D)


    # Optional: save
    import cv2
    cv2.imwrite("PointCloud_num_" + str(num_selected_sample) + "_label_" + str(label_test) + ".png", img)

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/WORK/03-PointNet/Show_PointCloud"
import numpy as np

# Load the .npy file
data = np.load('radar_data_test.npy')
point0 = data[0]
point3D = point0[:, :3]

# Print the shape of the data
print("Shape of radar_data_test.npy:", data.shape)
print("Shape of point0:", point0.shape)
print("Shape of point3D:", point3D.shape)


print("="*50)
labels = np.load('radar_labels_test.npy')
label0 = labels[0]

print("Shape of radar_labels_test.npy:", labels.shape)
print("Shape of label0:", label0)

"""---
---
---
"""

from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.utils.data
from torch.autograd import Variable
import numpy as np
import torch.nn.functional as F


class STN3d(nn.Module):
    def __init__(self):
        super(STN3d, self).__init__()
        self.conv1 = torch.nn.Conv1d(5, 64, 1) #3, 64, 1
        self.conv2 = torch.nn.Conv1d(64, 128, 1)
        self.conv3 = torch.nn.Conv1d(128, 1024, 1)
        self.fc1 = nn.Linear(1024, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, 9)
        self.relu = nn.ReLU()

        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(128)
        self.bn3 = nn.BatchNorm1d(1024)
        self.bn4 = nn.BatchNorm1d(512)
        self.bn5 = nn.BatchNorm1d(256)


    def forward(self, x):
        batchsize = x.size()[0]
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        x = torch.max(x, 2, keepdim=True)[0]
        x = x.view(-1, 1024)

        x = F.relu(self.bn4(self.fc1(x)))
        x = F.relu(self.bn5(self.fc2(x)))
        x = self.fc3(x)

        iden = Variable(torch.from_numpy(np.array([1,0,0,0,1,0,0,0,1]).astype(np.float32))).view(1,9).repeat(batchsize,1)
        if x.is_cuda:
            iden = iden.cuda()
        x = x + iden
        x = x.view(-1, 3, 3)
        return x


class STNkd(nn.Module):
    def __init__(self, k=64):
        super(STNkd, self).__init__()
        self.conv1 = torch.nn.Conv1d(k, 64, 1)
        self.conv2 = torch.nn.Conv1d(64, 128, 1)
        self.conv3 = torch.nn.Conv1d(128, 1024, 1)
        self.fc1 = nn.Linear(1024, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, k*k)
        self.relu = nn.ReLU()

        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(128)
        self.bn3 = nn.BatchNorm1d(1024)
        self.bn4 = nn.BatchNorm1d(512)
        self.bn5 = nn.BatchNorm1d(256)

        self.k = k

    def forward(self, x):
        batchsize = x.size()[0]
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        x = torch.max(x, 2, keepdim=True)[0]
        x = x.view(-1, 1024)

        x = F.relu(self.bn4(self.fc1(x)))
        x = F.relu(self.bn5(self.fc2(x)))
        x = self.fc3(x)

        iden = Variable(torch.from_numpy(np.eye(self.k).flatten().astype(np.float32))).view(1,self.k*self.k).repeat(batchsize,1)
        if x.is_cuda:
            iden = iden.cuda()
        x = x + iden
        x = x.view(-1, self.k, self.k)
        return x

class PointNetfeat(nn.Module):
    def __init__(self, global_feat = True, feature_transform = False):
        super(PointNetfeat, self).__init__()
        self.stn = STN3d()
        self.conv1 = torch.nn.Conv1d(3, 64, 1)
        self.conv2 = torch.nn.Conv1d(64, 128, 1)
        self.conv3 = torch.nn.Conv1d(128, 1024, 1)
        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(128)
        self.bn3 = nn.BatchNorm1d(1024)
        self.global_feat = global_feat
        self.feature_transform = feature_transform
        if self.feature_transform:
            self.fstn = STNkd(k=64)

    def forward(self, x):
        n_pts = x.size()[2]
        trans = self.stn(x)
        x = x.transpose(2, 1)
        x = torch.bmm(x, trans)
        x = x.transpose(2, 1)
        x = F.relu(self.bn1(self.conv1(x)))

        if self.feature_transform:
            trans_feat = self.fstn(x)
            x = x.transpose(2,1)
            x = torch.bmm(x, trans_feat)
            x = x.transpose(2,1)
        else:
            trans_feat = None

        pointfeat = x
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.bn3(self.conv3(x))
        x = torch.max(x, 2, keepdim=True)[0]
        x = x.view(-1, 1024)
        if self.global_feat:
            return x, trans, trans_feat
        else:
            x = x.view(-1, 1024, 1).repeat(1, 1, n_pts)
            return torch.cat([x, pointfeat], 1), trans, trans_feat

class PointNetCls(nn.Module):
    def __init__(self, k=2, feature_transform=False):
        super(PointNetCls, self).__init__()
        self.feature_transform = feature_transform
        self.feat = PointNetfeat(global_feat=True, feature_transform=feature_transform)
        self.fc1 = nn.Linear(1024, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, k)
        self.dropout = nn.Dropout(p=0.3)
        self.bn1 = nn.BatchNorm1d(512)
        self.bn2 = nn.BatchNorm1d(256)
        self.relu = nn.ReLU()

    def forward(self, x):
        x, trans, trans_feat = self.feat(x)
        x = F.relu(self.bn1(self.fc1(x)))
        x = F.relu(self.bn2(self.dropout(self.fc2(x))))
        x = self.fc3(x)
        return F.log_softmax(x, dim=1), trans, trans_feat


class PointNetDenseCls(nn.Module):
    def __init__(self, k = 2, feature_transform=False):
        super(PointNetDenseCls, self).__init__()
        self.k = k
        self.feature_transform=feature_transform
        self.feat = PointNetfeat(global_feat=False, feature_transform=feature_transform)
        self.conv1 = torch.nn.Conv1d(1088, 512, 1)
        self.conv2 = torch.nn.Conv1d(512, 256, 1)
        self.conv3 = torch.nn.Conv1d(256, 128, 1)
        self.conv4 = torch.nn.Conv1d(128, self.k, 1)
        self.bn1 = nn.BatchNorm1d(512)
        self.bn2 = nn.BatchNorm1d(256)
        self.bn3 = nn.BatchNorm1d(128)

    def forward(self, x):
        batchsize = x.size()[0]
        n_pts = x.size()[2]
        x, trans, trans_feat = self.feat(x)
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        x = self.conv4(x)
        x = x.transpose(2,1).contiguous()
        x = F.log_softmax(x.view(-1,self.k), dim=-1)
        x = x.view(batchsize, n_pts, self.k)
        return x, trans, trans_feat

def feature_transform_regularizer(trans):
    d = trans.size()[1]
    batchsize = trans.size()[0]
    I = torch.eye(d)[None, :, :]
    if trans.is_cuda:
        I = I.cuda()
    loss = torch.mean(torch.norm(torch.bmm(trans, trans.transpose(2,1)) - I, dim=(1,2)))
    return loss

if __name__ == '__main__':
    sim_data = Variable(torch.rand(32,5,1024)) #(32,3,2500)
    trans = STN3d()
    out = trans(sim_data)
    print('stn', out.size())
    print('loss', feature_transform_regularizer(out))

    sim_data_64d = Variable(torch.rand(32, 64, 2500))
    trans = STNkd(k=64)
    out = trans(sim_data_64d)
    print('stn64d', out.size())
    print('loss', feature_transform_regularizer(out))

    pointfeat = PointNetfeat(global_feat=True)
    out, _, _ = pointfeat(sim_data)
    print('global feat', out.size())

    pointfeat = PointNetfeat(global_feat=False)
    out, _, _ = pointfeat(sim_data)
    print('point feat', out.size())

    cls = PointNetCls(k = 5)
    out, _, _ = cls(sim_data)
    print('class', out.size())

    seg = PointNetDenseCls(k = 3)
    out, _, _ = seg(sim_data)
    print('seg', out.size())